# CMake generated Testfile for 
# Source directory: /Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd
# Build directory: /Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(BucketEliminationGraphDecompositionAlgorithmTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/BucketEliminationGraphDecompositionAlgorithmTest")
add_test(BucketEliminationTreeDecompositionAlgorithmTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/BucketEliminationTreeDecompositionAlgorithmTest")
add_test(ConnectedComponentAlgorithmTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/ConnectedComponentAlgorithmTest")
add_test(FactoryTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/FactoryTest")
add_test(FilteredHyperedgeCollectionTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/FilteredHyperedgeCollectionTest")
add_test(GraphDecompositionTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/GraphDecompositionTest")
add_test(GraphLabelingTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/GraphLabelingTest")
add_test(GraphTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/GraphTest")
add_test(HelperTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/HelperTest")
add_test(HyperedgeTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/HyperedgeTest")
add_test(HypergraphTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/HypergraphTest")
add_test(HypertreeDecompositionAlgorithmTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/HypertreeDecompositionAlgorithmTest")
add_test(HypertreeDecompositionTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/HypertreeDecompositionTest")
add_test(IteratorTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/IteratorTest")
add_test(LabelCollectionTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/LabelCollectionTest")
add_test(LabeledDirectedGraphTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/LabeledDirectedGraphTest")
add_test(LabeledDirectedMultiGraphTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/LabeledDirectedMultiGraphTest")
add_test(LabeledGraphTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/LabeledGraphTest")
add_test(LabeledHypergraphTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/LabeledHypergraphTest")
add_test(LabeledMultiGraphTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/LabeledMultiGraphTest")
add_test(LabelingCollectionTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/LabelingCollectionTest")
add_test(LibraryInstanceTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/LibraryInstanceTest")
add_test(ManipulationOperationTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/ManipulationOperationTest")
add_test(MaximumCardinalitySearchOrderingAlgorithmTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/MaximumCardinalitySearchOrderingAlgorithmTest")
add_test(MinDegreeOrderingAlgorithmTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/MinDegreeOrderingAlgorithmTest")
add_test(MinFillOrderingAlgorithmTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/MinFillOrderingAlgorithmTest")
add_test(MultiGraphTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/MultiGraphTest")
add_test(MultiHypergraphTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/MultiHypergraphTest")
add_test(PathDecompositionTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/PathDecompositionTest")
add_test(PathTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/PathTest")
add_test(PostProcessingPathDecompositionAlgorithmTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/PostProcessingPathDecompositionAlgorithmTest")
add_test(SetCoverAlgorithmTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/SetCoverAlgorithmTest")
add_test(TreeDecompositionOptimizationTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/TreeDecompositionOptimizationTest")
add_test(TreeDecompositionTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/TreeDecompositionTest")
add_test(TreeTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/TreeTest")
add_test(VertexSelectionStrategyTest "/Users/wei/Desktop/PhD_experiment/RNARedPrint-master/lib/htd-master/test/htd/VertexSelectionStrategyTest")
