#!/usr/bin/env python3

"""
Wrapper for the RNARedPrint executable.

This lets wrapper the executable find the java tree 
decomposition library, regardless of where it is called
from
"""

import os
import sys
import subprocess

binpath = os.path.dirname(__file__)

relshared = "../share/RNARedPrint"
prefix = os.path.join(binpath,relshared)

prog = "RNARedPrint"
prog = os.path.join(prefix,prog)

cmd = [prog]
cmd.extend(sys.argv[1:])
cmd.extend([ "--prefix",prefix+"/" ])


subprocess.call( cmd )
